export const soilHealthScore={
    "Nutrient Deficient":1,
    "Balanced":2,
    "Acidic(pH < 5.5)":3,
    "Low Phosphorus":4,
    "Sandy Soil":5,
    "Waterlogged Soil":6,
    "Low Organic Matter":7,
    "Alkaline(pH > 8)":8,
    "Nutrient Rich":9,
    "Saline Soil":10,
    "High Organic Matter":11,
    "Calcareous Soil":12,
    "Low Potassium":13,
    "High Clay Content":14,
    "Eroded Soil":15,
    "Low Nitrogen":16,
    "Loamy Soil(Well Drained)":17,
    "Peaty soil(High Organic)":18,
    "High Magnesium":19,
    "Low Calcium":20,
    "Compacted Soil":21,
    "High Sodium(Sodic Soil)":22,
    "Heavy Meatal Contaminated":23,
    "Low Iron":24,
    "Low Sulfer":25,
    "Low Zinc":26,
    "Moderate Organic Matter":27,
}

export const weatherHealthScore={
    "Cool & Dry":1,
    "Warm & Humid":2,
    "Hot & Wet":3,
    "Mild & Dry":4,
    "Hot & Arid":5,
    "Moderate & Humid":6,
    "Mild & Moderate":7,
    "Warm & Dry":8,
    "Warm & Wet":9,
    "Hot & Humid":10,
    "Wet & Warm":11,
    "Hot & Dry":12,
    "Cool & Wet":13,
    "Cool & Humid":14,
    "Cool Moderate":15,
    "Cool & Moist":16,
    "Mild & Humid":17,
    "Moderate & Dry":18,
    "Moderate & Wet":19,
    "Warm & Sunny":20,
    "Moderate & Sunny":21,
}

export const growthStageScore={
    "Germination":1,
    "Vegetative":2,
    "Flowering":3,
    "Fruiting":4,
   "Maturity":5,
}